#!/usr/bin/env bash

export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.local/pipx-venv/bin:$PATH"
export DEBIAN_FRONTEND=noninteractive
export NONINTERACTIVE=1

set -e

if [[ -f /etc/os-release ]]; then
    . /etc/os-release
fi

if [[ -n "$ID_LIKE" ]]; then
    OS=$(echo $ID_LIKE | cut -d " " -f 1 | tr '[:upper:]' '[:lower:]')
fi

if [[ -n "$ID" ]]; then
    OS=$(echo $ID | tr '[:upper:]' '[:lower:]')
fi

if [[ $(uname) == 'Darwin' ]]; then
    OS='mac'
fi

function setup_arch(){
    if ! command -v python > /dev/null 2>&1 && ! command -v python3 > /dev/null 2>&1; then
        sudo pacman -Sy
        sudo pacman -S --noconfirm python
    fi

    if ! command -v pipx > /dev/null 2>&1; then
        sudo pacman -Sy
        sudo pacman -S --noconfirm python-pipx
    fi
}

function setup_ubuntu(){
    if ! command -v python > /dev/null 2>&1 && ! command -v python3 > /dev/null 2>&1; then
        sudo add-apt-repository universe
        sudo apt-get -y update
        sudo apt-get -y install python3 python-is-python3
    fi

    if ! command -v pipx > /dev/null 2>&1; then
        sudo apt-get -y update
        sudo apt-get -y install pipx
    fi
}

function setup_mac(){
    sudo -v
    pmset noidle &

    if ! command -v brew > /dev/null 2>&1; then
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    fi

    if ! command -v python > /dev/null 2>&1 && ! command -v python3 > /dev/null 2>&1; then
        brew install python3
    fi

    if ! command -v pipx > /dev/null 2>&1; then
        brew install pipx
    fi
}

case $OS in
    "arch") setup_arch ;;
    "ubuntu") setup_ubuntu ;;
    "mac") setup_mac ;;
    *)
        echo "Not supported yet"
        exit 1
        ;;
esac

clear
if ! command -v ansible > /dev/null 2>&1; then
    pipx install --include-deps ansible
    sleep 1
fi

PLAYBOOK="local.$OS.yml"
ARGS="--ask-become "

if (( $# <= 0 )); then
    ARGS+="--ask-vault-password "
fi

if [[ -n "$WSL_DISTRO_NAME" ]]; then
    ARGS+="--skip-tags apps hyprland "
fi

clear
ansible-playbook $PLAYBOOK $ARGS ${@}
