- name: Installing flameshot dependencies using pacman
  become: true
  community.general.pacman:
      update_cache: true
      state: 'latest'
      name:
          - qt5-base
          - qt5-tools
          - qt5-svg
          - kguiaddons
          - kguiaddons5
          - grim
          - slurp
  when: ansible_distribution == ARCH
  tags:
      - apps

- name: Installing flameshot dependencies using apt
  become: true
  ansible.builtin.apt:
      update_cache: true
      state: 'latest'
      name:
          - xdg-desktop-portal-gnome
          - grim
          - slurp
          - libkf5guiaddons-dev
          - qtbase5-dev
          - qttools5-dev-tools
          - qttools5-dev
          - libqt5dbus5
          - libqt5network5
          - libqt5core5a
          - libqt5widgets5
          - libqt5gui5
          - libqt5svg5-dev
  when: ansible_distribution == UBUNTU
  tags:
      - apps

- name: Installing flameshot using homebrew
  community.general.homebrew:
      state: 'latest'
      name: 'flameshot'
  when: ansible_distribution == MAC
  tags:
      - apps

- name: Download flameshot package repository
  ansible.builtin.git:
      repo: 'https://github.com/flameshot-org/flameshot.git'
      dest: '{{ HOME }}/flameshot'
      depth: 1
      recursive: true
  when: ansible_distribution == ARCH or ansible_distribution == UBUNTU
  tags:
      - apps

- name: Building flameshot for linux
  ansible.builtin.shell: |
      cd {{ HOME }}/flameshot
      mkdir build
      cd build
      cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DUSE_WAYLAND_CLIPBOARD=true -DUSE_WAYLAND_GRIM=ON ../
      make
  when: ansible_distribution == ARCH or ansible_distribution == UBUNTU
  tags:
      - apps

- name: Installing flameshot
  become: true
  ansible.builtin.shell: |
      cd {{ HOME }}/flameshot
      cmake --install build
  when: ansible_distribution == ARCH or ansible_distribution == UBUNTU
  tags:
      - apps
