- name: Install neovim dependencies using pacman
  become: true
  community.general.pacman:
      update_cache: true
      state: 'latest'
      name:
          - gettext
          - tree-sitter-cli
  when: ansible_distribution == ARCH
  tags:
      - neovim

- name: Install neovim dependencies using apt
  become: true
  ansible.builtin.apt:
      update_cache: true
      allow_downgrade: true
      state: 'latest'
      name:
          - gettext
          - tree-sitter-cli
  when: ansible_distribution == UBUNTU
  tags:
      - neovim

- name: Install neovim dependencies using homebrew
  community.general.homebrew:
      state: 'latest'
      name:
          - gettext
          - tree-sitter
  when: ansible_distribution == MAC
  tags:
      - neovim

- name: Ensure neovim config clean
  ansible.builtin.file:
      dest: '{{ XDG_CONFIG_HOME }}/nvim'
      state: 'absent'
  tags:
      - neovim

- name: Downloading neovim package repository
  ansible.builtin.git:
      repo: 'https://github.com/neovim/neovim.git'
      dest: '{{ HOME }}/neovim'
      version: 'stable'
      recursive: true
      update: true
      depth: 1
  tags:
      - neovim

- name: Downloading neovim config repository
  ansible.builtin.git:
      repo: 'http://github.com/akbarsanihasan/nvimrc.git'
      dest: '{{ playbook_dir }}/Nvimrc'
      recursive: true
      accept_hostkey: true
      update: false
      depth: 1
  tags:
      - neovim

- name: Link nvimrc to config
  ansible.builtin.file:
      src: '{{ playbook_dir }}/Nvimrc'
      dest: '{{ XDG_CONFIG_HOME }}/nvim'
      state: 'link'

- name: Building neovim package
  ansible.builtin.shell: |
      cd {{ HOME }}/neovim

      make distclean 
      make deps

      make CMAKE_BUILD_TYPE=RelWithDebInfo -j$(nproc)
  tags:
      - neovim

- name: Installing neovim package
  become: true
  ansible.builtin.shell: |
      cd {{ HOME }}/neovim
      make install
  tags:
      - neovim
