- name: Installing opam using pacman
  become: true
  community.general.pacman:
      update_cache: true
      state: 'latest'
      name: opam
  when:
      - ansible_distribution == ARCH
  tags:
      - ocaml
      - neovim

- name: Installing opam using apt
  become: true
  ansible.builtin.apt:
      update_cache: true
      allow_downgrade: true
      state: 'latest'
      name: opam
  when:
      - ansible_distribution == UBUNTU
  tags:
      - ocaml
      - neovim

- name: Installing opam using homebrew
  community.general.homebrew:
      state: 'latest'
      name: opam
  when:
      - ansible_distribution  == MAC
  tags:
      - ocaml
      - neovim

- name: Initialize opam package manager
  ansible.builtin.shell: 'bash -c "opam init --disable-sandboxing -y"'
  tags:
      - ocaml
      - neovim

- name: Setting ocaml environment
  ansible.builtin.blockinfile:
      path: '{{ HOME }}/{{ item }}'
      state: 'present'
      create: 'yes'
      prepend_newline: true
      marker: '#--------- {mark} ---------#'
      marker_begin: 'StartOcaml'
      marker_end: 'EndOcaml'
      block: |
          eval $(opam env)
          [[ -r "$HOME/.opam/opam-init/init.sh" ]] && . "$HOME/.opam/opam-init/init.sh" > /dev/null 2> /dev/null || true
  loop:
      - .zshrc
      - .bashrc
  tags:
      - ocaml
      - neovim
