- name: Download forbidden installsripts
  ansible.builtin.git:
      repo: 'git@github.com:akbarsanihasan/{{ item.repo }}.git'
      dest: '{{ HOME }}/.forbidden/{{ item.name }}'
      depth: 1
      update: false
      accept_hostkey: true
  loop:
      - {repo: forbidden-archscripts, name: archscritps}
      - {repo: forbidden-archinstall, name: archinstall}
  tags:
      - personal
